interface StatusBadgeProps {
  status: string;
}

const toneByStatus: Record<string, string> = {
  new: "status-badge status-new",
  seen: "status-badge status-seen",
  applied: "status-badge status-applied",
  skipped: "status-badge status-skipped",
  queued: "status-badge status-seen",
  preparing: "status-badge status-seen",
  awaiting_review: "status-badge status-review",
  ready_to_fill: "status-badge status-ready",
  filling: "status-badge status-live",
  awaiting_manual: "status-badge status-review",
  prefill_completed: "status-badge status-submit",
  awaiting_submit_confirmation: "status-badge status-submit",
  submitting: "status-badge status-live",
  submitted: "status-badge status-applied",
  failed: "status-badge status-failed",
  aborted: "status-badge status-skipped",
  greenhouse: "status-badge status-live",
  lever: "status-badge status-live",
  moka: "status-badge status-live",
  portal: "status-badge status-review",
  generic: "status-badge status-seen",
  jsonld: "status-badge status-seen",
  feishu_sheet: "status-badge status-review",
  status: "status-badge status-seen",
  discovery: "status-badge status-live",
  review: "status-badge status-review",
  fill: "status-badge status-ready",
  manual: "status-badge status-review",
  submit: "status-badge status-submit",
  error: "status-badge status-failed",
  text: "status-badge status-seen",
  email: "status-badge status-seen",
  tel: "status-badge status-seen",
  url: "status-badge status-seen",
  textarea: "status-badge status-seen",
  select: "status-badge status-ready",
  radio: "status-badge status-ready",
  checkbox: "status-badge status-ready",
  file: "status-badge status-live",
  date: "status-badge status-seen",
  number: "status-badge status-seen",
  hidden: "status-badge status-skipped",
  unknown: "status-badge status-seen"
};

const labelByStatus: Record<string, string> = {
  new: "新发现",
  seen: "已查看",
  applied: "已投递",
  skipped: "已跳过",
  queued: "排队中",
  preparing: "准备中",
  awaiting_review: "待确认",
  ready_to_fill: "可开始填写",
  filling: "填写中",
  awaiting_manual: "等待人工处理",
  prefill_completed: "预填完成",
  awaiting_submit_confirmation: "待最终提交",
  submitting: "提交中",
  submitted: "已提交",
  failed: "失败",
  aborted: "已中止",
  greenhouse: "Greenhouse",
  lever: "Lever",
  moka: "Moka",
  portal: "通用入口",
  generic: "通用站点",
  jsonld: "结构化职位页",
  feishu_sheet: "飞书表格",
  status: "状态",
  discovery: "发现",
  review: "确认",
  fill: "填写",
  manual: "人工处理",
  submit: "提交",
  error: "错误",
  text: "文本",
  email: "邮箱",
  tel: "电话",
  url: "链接",
  textarea: "多行文本",
  select: "下拉",
  radio: "单选",
  checkbox: "多选",
  file: "文件",
  date: "日期",
  number: "数字",
  hidden: "隐藏字段",
  unknown: "未知字段"
};

export const getStatusLabel = (status: string): string =>
  labelByStatus[status] ?? status.replace(/_/g, " ");

export const StatusBadge = ({ status }: StatusBadgeProps) => (
  <span className={toneByStatus[status] ?? "status-badge"}>{getStatusLabel(status)}</span>
);
